baseurl = "https://www.richgamer.net/"
title = "Simple Blox"
author = "RG"
copyright = 'Copyright © by <a href="/">RG</a>'
canonifyurls = true
paginate = 3
theme = "simpleblox"

[menu]
    [[menu.main]]
    name = "Home"
    url = "/"
    weight = "-10"

[params]
facebook = "#"
twitter = "#"
github = "#"
